{% set name = "pytest-regtest" %}
{% set version = "2.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d9cf0db9d958b4e3fedcf84ff5ac4247b24663eb1bf9011568123fccd34b391f

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling >=1.12.2
  run:
    - pytest >=4.1.0
    - python >={{ python_min }}

test:
  commands:
    - py.test --traceconfig | grep pytest-regtest-{{ version }}
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://gitlab.com/uweschmitt/pytest-regtest
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: pytest plugin for regression tests
  dev_url: https://gitlab.com/uweschmitt/pytest-regtest

extra:
  recipe-maintainers:
    - danieljahn
    - dbast
