{% set name = "pytest-regtest" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 348f9f23b45d5a674fbdf2a70429221242063baf6a1521f30fb0aa03f7bea5db

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - pytest >=4.1.0
    - python >=3.6

test:
  commands:
    - py.test --traceconfig | grep pytest-regtest-{{ version }}
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/uweschmitt/pytest-regtest
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: pytest plugin for regression tests
  dev_url: https://gitlab.com/uweschmitt/pytest-regtest

extra:
  recipe-maintainers:
    - danieljahn
    - dbast
