{% set name = "pytest-regtest" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8212a6e147abcf6d4e295bd74e6adb922ec541f0fcb2d06fc91c344ab4dbcc96

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.9
    - hatchling >=1.12.2
  run:
    - pytest >=4.1.0
    - python >=3.9

test:
  commands:
    - py.test --traceconfig | grep pytest-regtest-{{ version }}
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/uweschmitt/pytest-regtest
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: pytest plugin for regression tests
  dev_url: https://gitlab.com/uweschmitt/pytest-regtest

extra:
  recipe-maintainers:
    - danieljahn
    - dbast
