travis:
  secure:
    BINSTAR_TOKEN: VUlWSNru9xmWgs1XmYIZAGwm4gilavTbEtUbQUcmBuBFS0u2Ur8NFU2yVEcQk1MGHHInz5Tga9P5auhTM4Z7vGara0Ub3W+yrCVIUb8QMr/PuravDCRUqS9DvaidW8EtB8F4PTuRevXBq1XdXWmWSBgk7/MyGrTXCeZ6avvppb/t1MKbcIoDCYgxj+WU7cdxMFKfYadW4N5ZNdQn/eBDmNmsKFedfnqAYc9vDXQVdbj9xoqPr79JxKDmeM+olwco+f5oJhiI3cKcm5xfuy0MG4bttFsShf+f3JgX8Skuvrr4LGWQboTu056bRZUW77eDthc4rvTepDVYJhaOrgT8/1H8u999I/wi67WdeBy5eouFAriy+1pa7GfAaQrR+oeGeVom7CSy4n18xiyxQ4ToYo0RqgNWEY3C3ZisfeE8ZE13n6RvkOMxiZseejbbXg8HpkV0jv3oGgVp7jNo19IrQZOa1j1LjHE9C5YgxxQWVEA34KZ1Sh9Zq2gC78ZQD15a8pf8B5hdy/7V5QAyQnUd0Pi1ii9SHIQS43J9q5RjG1h42fV9Z6J4KwOXZhn/gAj9yYZqbR+G3KBnoIM4fGEJMRD0eOLSolnip8aZzwkdBp03aTfGLlfHEb6TqNuoIGsSk98wucyyHt6JTcfkcPkWZi/XrNwWQqWWdh9mW8rdUr4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
